name: Deploy Kybus.Enigma to GPR

on:
  deployment:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack NuGet Package
      run: dotnet pack -c Release -o nuget_builds
    - name: Prepare secrets
      run: sed -i 's/##TOKEN##/${{ secrets.PACKAGE_TOKEN }}/g' nuget.config
    - name: Push to GitHub Packages
      run: dotnet nuget push "nuget_builds/Kybus.Enigma.1.0.0.nupkg" --source "https://nuget.pkg.github.com/dschemp/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}"
