name: Kybus.Enigma
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Push latest package to GPR
      run: sed -i 's/##TOKEN##/${{ secrets.PACKAGE_TOKEN }}/g' nuget.config && dotnet nuget push './src/Kybus.Enigma.1.0.0.nupkg' --source "github"
